//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemadeAlmacenAPI.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Sistema_de_Almacen_Entities : DbContext
    {
        public Sistema_de_Almacen_Entities()
            : base("name=Sistema_de_Almacen_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Centro_Costo> Centro_Costo { get; set; }
        public virtual DbSet<Cuenta> Cuenta { get; set; }
        public virtual DbSet<Detalle_Entrada> Detalle_Entrada { get; set; }
        public virtual DbSet<Detalle_Salida> Detalle_Salida { get; set; }
        public virtual DbSet<Entradas> Entradas { get; set; }
        public virtual DbSet<Inventario> Inventario { get; set; }
        public virtual DbSet<Linea> Linea { get; set; }
        public virtual DbSet<Movimientos> Movimientos { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<Salidas> Salidas { get; set; }
        public virtual DbSet<Sedes> Sedes { get; set; }
        public virtual DbSet<Unidades> Unidades { get; set; }
        public virtual DbSet<Unidades_Medida> Unidades_Medida { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
        public virtual DbSet<Articulo> Articulo { get; set; }
    }
}
