//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemadeAlmacenAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detalle_Salida
    {
        public int ID_DetalleSalida { get; set; }
        public Nullable<int> ID_Salida { get; set; }
        public Nullable<int> ID_Articulo { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<decimal> Precio_Unitario { get; set; }
        public Nullable<decimal> Total { get; set; }
    
        public virtual Salidas Salidas { get; set; }
        public virtual Articulo Articulo { get; set; }
    }
}
