//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemadeAlmacenAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Entradas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Entradas()
        {
            this.Detalle_Entrada = new HashSet<Detalle_Entrada>();
        }
    
        public int ID_Entradas { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> ID_Movimiento { get; set; }
        public Nullable<int> ID_Proveedores { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> ID_Sede { get; set; }
    
        public virtual Movimientos Movimientos { get; set; }
        public virtual Proveedores Proveedores { get; set; }
        public virtual Sedes Sedes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Entrada> Detalle_Entrada { get; set; }
    }
}
