//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemadeAlmacenAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Salidas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salidas()
        {
            this.Detalle_Salida = new HashSet<Detalle_Salida>();
        }
    
        public int ID_Salida { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<System.TimeSpan> Hora { get; set; }
        public Nullable<int> ID_Movimiento { get; set; }
        public Nullable<int> ID_CenCost { get; set; }
        public Nullable<int> ID_Unidad { get; set; }
        public Nullable<int> ID_Personal { get; set; }
        public string Comentarios { get; set; }
        public Nullable<int> ID_Sede { get; set; }
    
        public virtual Centro_Costo Centro_Costo { get; set; }
        public virtual Movimientos Movimientos { get; set; }
        public virtual Personal Personal { get; set; }
        public virtual Sedes Sedes { get; set; }
        public virtual Unidades Unidades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle_Salida> Detalle_Salida { get; set; }
    }
}
