//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemadeAlmacenAPI.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int ID_Usuario { get; set; }
        public string Nombre_Usuario { get; set; }
        public string Contrasenia { get; set; }
        public Nullable<int> ID_Roles { get; set; }
        public Nullable<int> ID_Sede { get; set; }
    
        public virtual Roles Roles { get; set; }
        public virtual Sedes Sedes { get; set; }
    }
}
